<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en_US" xml:lang="en_US">
 <head>
  <title>Component test: undefined components</title>
  <style type="text/css"><!--

div.hello{
	background: #ffcccc;
}
  
  -->  
  </style>
 </head>
 <body>
  <h1>Component test: undefined components</h1>
  <p>The example checks, whether the undefined components work properly.</p>

  <opt:snippet name="dupa">
  <com:div>
  	<p>{$opt.component.title}: <opt:display /></p>
  	<opt:onEvent name="error">
  		<p style="color: red; ">An error occured: {$opt.component.msg}</p>
  	</opt:onEvent>
  </com:div>
  </opt:snippet>

  <form method="post" action="test_components_3.php">

  <!-- this defined component allows to select the number of fields to display -->
  <opt:select str:name="number" datasource="$numbers" template="dupa">
  	<opt:set name="selected" value="$sNumber"/>
  	<opt:set name="title" str:value="Choose the number of fields"/>
  </opt:select>

  <!-- display the components generated by the script. -->
  <opt:section name="items">
  <opt:component from="$items.component" template="dupa" />
  </opt:section>
  
  <p><input type="submit" value="OK"/></p>
  </form>
 </body>
</html>
