<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<opt:root>
<opt:prolog str:encoding="UTF-8" />
<opt:dtd template="xhtml11"/>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en_US" xml:lang="en_US">
 <head>
  <title>DTD test</title>
 </head>
 <body>
  <h1>DTD test</h1>
  <p>In this example, the prolog is generated by OPT instruction, as well as DTD. The opt:dtd instruction contains
  several DTD templates that can be easily used in your templates:</p>
  <ol>
  	<li>xhtml10strict</li>
  	<li>xhtml10transitional</li>
  	<li>xhtml10frameset</li>
  	<li>xhtml11</li>
  	<li>html40</li>
  </ol>
 </body>
</html>
</opt:root>