<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<opt:root>
<opt:prolog str:encoding="UTF-8" />
<opt:dtd><![CDATA[
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
]]></opt:dtd>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en_US" xml:lang="en_US">
 <head>
  <title>DTD test</title>
 </head>
 <body>
  <h1>DTD test</h1>
  <p>In this example, the prolog is generated by OPT instruction. The DTD is typed manually, however, inside
  the opt:dtd instruction, which allows to use the CDATA section without worrying about displaying it.</p>
 </body>
</html>
</opt:root>